language: c

compiler:
    - gcc
    - clang

env:
    - BUILDTOOL=cmake
    - BUILDTOOL=autotools

before_script:
    - echo 'APT::Install-Recommends "false";' | sudo tee -a /etc/apt/apt.conf
    - sudo apt-get update -qq
    - sudo apt-get -y install devscripts equivs python-pip libenchant-dev autopoint
    - sudo mk-build-deps -i debian/control
    - sudo pip install msgcheck pylint

script:
    - ./scripts/build.sh
    - msgcheck po/*.po
    - pylint doc/docgen.py

after_success:
    - weechat --help
    - weechat -r /quit
